name: ziwei
options:
  bundleIdPrefix: com.ziweixingyu
  deploymentTarget:
    iOS: "16.0"
targets:
  ziwei:
    type: application
    platform: iOS
    sources:
      - ziwei
    settings:
      GENERATE_INFOPLIST_FILE: true
      INFOPLIST_KEY_UIApplicationSceneManifest_Generation: true
      INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: true
      INFOPLIST_KEY_UILaunchScreen_Generation: true
      "INFOPLIST_KEY_CFBundleDisplayName": "紫微星语"
      PRODUCT_BUNDLE_IDENTIFIER: com.ziweixingyu.ios
      SWIFT_VERSION: "5.9"
      MARKETING_VERSION: "1.0.0"
      CURRENT_PROJECT_VERSION: "1"
      CODE_SIGN_STYLE: Automatic
